//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U1     ЖЭУ111          Есенина 16")]
        public string UNIT1_name {
            get {
                return ((string)(this["UNIT1_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=\\\\sibsup\\DISTR\\test_admin\\db_admink" +
            "a.accdb")]
        public string db_adminkaConnectionString {
            get {
                return ((string)(this["db_adminkaConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\SolarWinds\\DameWare Remote Support\\")]
        public string dmwrPath_old {
            get {
                return ((string)(this["dmwrPath_old"]));
            }
            set {
                this["dmwrPath_old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\sibsup\\DISTR\\okhten_mmc.msc")]
        public string mmc {
            get {
                return ((string)(this["mmc"]));
            }
            set {
                this["mmc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\windows\\system32\\msinfo32.exe")]
        public string msinfo_xml {
            get {
                return ((string)(this["msinfo_xml"]));
            }
            set {
                this["msinfo_xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Acronis\\TrueImageHome\\TrueImageLauncher.exe")]
        public string acronis_xml {
            get {
                return ((string)(this["acronis_xml"]));
            }
            set {
                this["acronis_xml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\sibsup\\distr\\okhten\\user_find.ps1")]
        public string PsLogon {
            get {
                return ((string)(this["PsLogon"]));
            }
            set {
                this["PsLogon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2666")]
        public string phone_number {
            get {
                return ((string)(this["phone_number"]));
            }
            set {
                this["phone_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VKV2666")]
        public string phone_pass {
            get {
                return ((string)(this["phone_pass"]));
            }
            set {
                this["phone_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.0.20")]
        public string phone_server {
            get {
                return ((string)(this["phone_server"]));
            }
            set {
                this["phone_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("okhten")]
        public string phone_name {
            get {
                return ((string)(this["phone_name"]));
            }
            set {
                this["phone_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\okhten\\Desktop\\DameWare Mini Remote Control x64\\DWRCC.exe")]
        public string dmwrPath {
            get {
                return ((string)(this["dmwrPath"]));
            }
            set {
                this["dmwrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\okhten\\Desktop\\DameWare Mini Remote Control x64\\")]
        public string dmwrPath1 {
            get {
                return ((string)(this["dmwrPath1"]));
            }
            set {
                this["dmwrPath1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int call_status {
            get {
                return ((int)(this["call_status"]));
            }
            set {
                this["call_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int servise_int {
            get {
                return ((int)(this["servise_int"]));
            }
            set {
                this["servise_int"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int check_roll_dw {
            get {
                return ((int)(this["check_roll_dw"]));
            }
            set {
                this["check_roll_dw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asa(7port) -> hp(25port) ")]
        public string j83_label {
            get {
                return ((string)(this["j83_label"]));
            }
            set {
                this["j83_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Волков Д")]
        public string phone1_label {
            get {
                return ((string)(this["phone1_label"]));
            }
            set {
                this["phone1_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Рахмагов С")]
        public string phone2_label {
            get {
                return ((string)(this["phone2_label"]));
            }
            set {
                this["phone2_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Башкиров А")]
        public string phone3_label {
            get {
                return ((string)(this["phone3_label"]));
            }
            set {
                this["phone3_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Васильчук В")]
        public string phone4_label {
            get {
                return ((string)(this["phone4_label"]));
            }
            set {
                this["phone4_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Анохин")]
        public string phone5_label {
            get {
                return ((string)(this["phone5_label"]));
            }
            set {
                this["phone5_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Бужор")]
        public string phone6_label {
            get {
                return ((string)(this["phone6_label"]));
            }
            set {
                this["phone6_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ушаков")]
        public string phone7_label {
            get {
                return ((string)(this["phone7_label"]));
            }
            set {
                this["phone7_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Литвин")]
        public string phone8_label {
            get {
                return ((string)(this["phone8_label"]));
            }
            set {
                this["phone8_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шелепов")]
        public string phone9_label {
            get {
                return ((string)(this["phone9_label"]));
            }
            set {
                this["phone9_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шипачева")]
        public string phone10_label {
            get {
                return ((string)(this["phone10_label"]));
            }
            set {
                this["phone10_label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4399")]
        public string phone1_tel {
            get {
                return ((string)(this["phone1_tel"]));
            }
            set {
                this["phone1_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7223")]
        public string phone2_tel {
            get {
                return ((string)(this["phone2_tel"]));
            }
            set {
                this["phone2_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7224")]
        public string phone3_tel {
            get {
                return ((string)(this["phone3_tel"]));
            }
            set {
                this["phone3_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7111")]
        public string phone4_tel {
            get {
                return ((string)(this["phone4_tel"]));
            }
            set {
                this["phone4_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4499")]
        public string phone5_tel {
            get {
                return ((string)(this["phone5_tel"]));
            }
            set {
                this["phone5_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4433")]
        public string phone6_tel {
            get {
                return ((string)(this["phone6_tel"]));
            }
            set {
                this["phone6_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1111")]
        public string phone7_tel {
            get {
                return ((string)(this["phone7_tel"]));
            }
            set {
                this["phone7_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4411")]
        public string phone8_tel {
            get {
                return ((string)(this["phone8_tel"]));
            }
            set {
                this["phone8_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4444")]
        public string phone9_tel {
            get {
                return ((string)(this["phone9_tel"]));
            }
            set {
                this["phone9_tel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5606")]
        public string phone10_tel {
            get {
                return ((string)(this["phone10_tel"]));
            }
            set {
                this["phone10_tel"] = value;
            }
        }
    }
}
